# Generated by Django 2.1.7 on 2019-04-02 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_maker', models.CharField(max_length=254)),
                ('cheque_type', models.CharField(max_length=254)),
                ('cheque_number', models.CharField(max_length=254)),
                ('account_number', models.CharField(max_length=254)),
                ('routing_number', models.CharField(max_length=254)),
                ('date_of_issue', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
